"""1

Revision ID: fae4d77c65bb
Revises: 356e4a3e04a3
Create Date: 2017-05-11 16:55:21.020329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae4d77c65bb'
down_revision = '356e4a3e04a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('class_color', sa.String(), nullable=True))
    op.add_column('users', sa.Column('faction_color', sa.String(), nullable=True))
    op.add_column('users', sa.Column('wow_class', sa.String(), nullable=True))
    op.add_column('users', sa.Column('wow_faction', sa.String(), nullable=True))
    op.add_column('users', sa.Column('wow_races', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wow_races')
    op.drop_column('users', 'wow_faction')
    op.drop_column('users', 'wow_class')
    op.drop_column('users', 'faction_color')
    op.drop_column('users', 'class_color')
    # ### end Alembic commands ###
